### ISSUE TITLE
Translation Files for Module Options in wrong place

### ISSUE THREAD

**Issue by clro** [wallee-payment/oxid-4.9#1]
The translation files "wle\Wallee\views\admin\de\module_options" and "wle\Wallee\views\admin\en\module_options" must be placed hear "\wle\Wallee\Application\views\admin\de\module_options" and hear "\wle\Wallee\Application\views\admin\en\module_options" otherwise there is a Translation ERROR in Module Options Page.

**Comment by thomashunziker** [comment]
Dear Clro,

You closed the issue. Is it not relevant anymore?

Regards,
Thomas

**Comment by clro** [comment]
Hallo Thomas

I noticed that I added the issues to the wrong module version. I encountered these problems with the module for Oxid 4.10 and added them there.
https://github.com/wallee-payment/oxid-4.10

Regards
Claudia
